-- =====================================================================================================
-- Flyway V1 baseline — Full schema for Tissue (PostgreSQL 16)
--
-- Built from Hibernate ddl-auto=create (38 tables, @UniqueConstraint, generated columns)
-- + DDL script (trgm/constraints/ts-vector/GIN)
-- + FK indexes
-- =====================================================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE public.activity_log (
    actor_member_id bigint,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    member_id bigint,
    resource_id bigint,
    event_id uuid NOT NULL,
    activity_type character varying(255) NOT NULL,
    issue_key character varying(255),
    project_key character varying(255),
    resource_type character varying(255) NOT NULL,
    activity_data jsonb,
    changes jsonb,
    CONSTRAINT activity_log_activity_type_check CHECK (((activity_type)::text = ANY ((ARRAY['ISSUE_CREATED'::character varying, 'ISSUE_UPDATED'::character varying, 'ISSUE_DELETED'::character varying, 'ISSUE_RESTORED'::character varying, 'ISSUE_ASSIGNED'::character varying, 'ISSUE_UNASSIGNED'::character varying, 'ISSUE_WORKFLOW_TRANSITIONED'::character varying, 'ISSUE_STORY_POINT_CHANGED'::character varying, 'ISSUE_PARENT_CHANGED'::character varying, 'ISSUE_RELATION_ADDED'::character varying, 'ISSUE_RELATION_REMOVED'::character varying, 'ISSUE_REVIEW_REQUESTED'::character varying, 'ISSUE_REVIEW_SUBMITTED'::character varying, 'ISSUE_REVIEWER_ADDED'::character varying, 'ISSUE_REVIEWER_REMOVED'::character varying, 'ISSUE_COMMENT_ADDED'::character varying, 'ISSUE_COMMENT_UPDATED'::character varying, 'ISSUE_COMMENT_DELETED'::character varying, 'ISSUE_BRANCH_CONNECTED'::character varying, 'ISSUE_VCS_CONNECTION_LINKED'::character varying, 'ISSUE_WORKFLOW_TRANSITIONED_BY_SYSTEM'::character varying, 'SPRINT_STARTED'::character varying, 'SPRINT_COMPLETED'::character varying])::text[]))),
    CONSTRAINT activity_log_resource_type_check CHECK (((resource_type)::text = ANY ((ARRAY['ISSUE'::character varying, 'ISSUE_COMMENT'::character varying, 'SPRINT'::character varying, 'PROJECT'::character varying, 'PROJECT_MEMBER'::character varying])::text[])))
);

ALTER TABLE public.activity_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.admin_audit_log (
    actor_member_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    action character varying(255) NOT NULL,
    target_ref character varying(255),
    target_type character varying(255) NOT NULL,
    data jsonb,
    CONSTRAINT admin_audit_log_action_check CHECK (((action)::text = ANY ((ARRAY['CHANGE_SYSTEM_ROLE'::character varying, 'FORCE_WITHDRAW'::character varying, 'FORCE_RESTORE'::character varying, 'REVOKE_SESSIONS'::character varying, 'HARD_DELETE_PROJECT'::character varying, 'LOCK_MEMBER'::character varying, 'UNLOCK_MEMBER'::character varying, 'PURGE_MEMBER'::character varying, 'FORCE_PASSWORD_RESET'::character varying])::text[]))),
    CONSTRAINT admin_audit_log_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['MEMBER'::character varying, 'PROJECT'::character varying])::text[])))
);

ALTER TABLE public.admin_audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_identity (
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    member_id bigint NOT NULL,
    credential character varying(255),
    identifier character varying(255) NOT NULL,
    provider character varying(255) NOT NULL,
    CONSTRAINT auth_identity_provider_check CHECK (((provider)::text = ANY ((ARRAY['EMAIL'::character varying, 'USERNAME'::character varying, 'OIDC'::character varying])::text[])))
);

ALTER TABLE public.auth_identity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_identity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comment (
    archived boolean NOT NULL,
    is_edited boolean NOT NULL,
    soft_deleted boolean NOT NULL,
    archived_at timestamp(6) with time zone,
    author_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    parent_comment_id bigint,
    soft_deleted_at timestamp(6) with time zone,
    content text NOT NULL,
    issue_key character varying(255) NOT NULL
);

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.email_verification_token (
    verified boolean NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    token_value character varying(255) NOT NULL,
    verification_id character varying(255) NOT NULL,
    verified_token character varying(255)
);

ALTER TABLE public.email_verification_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.failed_email (
    retry_count integer NOT NULL,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    next_retry_at timestamp(6) with time zone NOT NULL,
    notification_id bigint NOT NULL,
    body text NOT NULL,
    error_message text,
    receiver_email character varying(255) NOT NULL,
    subject character varying(255) NOT NULL
);

ALTER TABLE public.failed_email ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.failed_email_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.field_option (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_field_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL
);

ALTER TABLE public.field_option ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.field_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue (
    archived boolean NOT NULL,
    count_based_progress integer,
    point_based_progress integer,
    soft_deleted boolean NOT NULL,
    story_point integer,
    archived_at timestamp(6) with time zone,
    assignee_id bigint,
    created_at timestamp(6) with time zone,
    created_by bigint,
    current_state_id bigint,
    due_at timestamp(6) with time zone,
    id bigint NOT NULL,
    issue_type_id bigint,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    parent_issue_id bigint,
    project_id bigint NOT NULL,
    resolved_at timestamp(6) with time zone,
    soft_deleted_at timestamp(6) with time zone,
    sprint_id bigint,
    started_at timestamp(6) with time zone,
    version bigint,
    content text,
    issue_key character varying(255) NOT NULL,
    priority character varying(255) NOT NULL,
    summary text,
    title character varying(255) NOT NULL,
    custom_fields jsonb,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (((((COALESCE(issue_key, ''::character varying))::text || ' '::text) || (COALESCE(title, ''::character varying))::text) || ' '::text) || COALESCE(content, ''::text)))) STORED,
    CONSTRAINT issue_priority_check CHECK (((priority)::text = ANY ((ARRAY['P0'::character varying, 'P1'::character varying, 'P2'::character varying, 'P3'::character varying, 'P4'::character varying])::text[])))
);

CREATE TABLE public.issue_attachment (
    created_at timestamp(6) with time zone,
    created_by bigint,
    file_size bigint NOT NULL,
    id bigint NOT NULL,
    issue_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    content_type character varying(255) NOT NULL,
    issue_key character varying(255) NOT NULL,
    original_filename character varying(255) NOT NULL,
    stored_filename character varying(255) NOT NULL,
    stored_path character varying(255) NOT NULL
);

ALTER TABLE public.issue_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_branch (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    pushed_at timestamp(6) with time zone,
    branch_name character varying(255) NOT NULL,
    branch_url character varying(255) NOT NULL,
    latest_commit_hash character varying(255),
    latest_commit_message character varying(255),
    latest_commit_url character varying(255),
    pusher_name character varying(255),
    repo_url character varying(255) NOT NULL
);

ALTER TABLE public.issue_branch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_field (
    "position" integer NOT NULL,
    required boolean NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_type_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    description character varying(255) NOT NULL,
    issue_field_type character varying(255) NOT NULL,
    CONSTRAINT issue_field_issue_field_type_check CHECK (((issue_field_type)::text = ANY ((ARRAY['TEXT'::character varying, 'INTEGER'::character varying, 'DECIMAL'::character varying, 'TIMESTAMP'::character varying, 'DATE'::character varying, 'BOOLEAN'::character varying, 'SELECT_OPTION'::character varying, 'PERCENTAGE'::character varying, 'CHECKLIST'::character varying])::text[])))
);

ALTER TABLE public.issue_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.issue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_relation (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    source_issue_id bigint NOT NULL,
    target_issue_id bigint NOT NULL,
    relation_type character varying(255) NOT NULL,
    CONSTRAINT issue_relation_relation_type_check CHECK (((relation_type)::text = ANY ((ARRAY['RELEVANT'::character varying, 'BLOCKS'::character varying, 'CAUSES'::character varying, 'DUPLICATES'::character varying])::text[])))
);

ALTER TABLE public.issue_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_reviewer (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    reviewer_id bigint NOT NULL,
    issue_key character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT issue_reviewer_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'CHANGES_REQUESTED'::character varying])::text[])))
);

ALTER TABLE public.issue_reviewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_reviewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_subscriber (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    subscribed_at timestamp(6) with time zone NOT NULL,
    subscriber_id bigint NOT NULL,
    issue_key character varying(255) NOT NULL
);

ALTER TABLE public.issue_subscriber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_subscriber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_tag (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    tag_id bigint NOT NULL,
    issue_key character varying(255) NOT NULL
);

ALTER TABLE public.issue_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue_type (
    system_provided boolean NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    workflow_id bigint NOT NULL,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    hierarchy character varying(255) NOT NULL,
    icon character varying(255) NOT NULL,
    CONSTRAINT issue_type_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[]))),
    CONSTRAINT issue_type_hierarchy_check CHECK (((hierarchy)::text = ANY ((ARRAY['EPIC'::character varying, 'STANDARD'::character varying, 'SUBTASK'::character varying, 'MICROTASK'::character varying])::text[]))),
    CONSTRAINT issue_type_icon_check CHECK (((icon)::text = ANY ((ARRAY['CIRCLE_FILLED'::character varying, 'CIRCLE_OUTLINE'::character varying, 'CIRCLE_DOT'::character varying, 'SQUARE_FILLED'::character varying, 'SQUARE_OUTLINE'::character varying, 'TRIANGLE_UP_FILLED'::character varying, 'TRIANGLE_DOWN_FILLED'::character varying, 'DIAMOND_FILLED'::character varying, 'DIAMOND_OUTLINE'::character varying, 'STAR_FILLED'::character varying, 'STAR_OUTLINE'::character varying, 'FLAG'::character varying, 'WARNING'::character varying, 'TARGET'::character varying, 'PROHIBITED'::character varying, 'CHECKBOX_CHECKED'::character varying, 'CHECKBOX_UNCHECKED'::character varying, 'ARROW_RIGHT'::character varying, 'ARROW_UP'::character varying, 'ARROW_DOWN'::character varying, 'CHEVRON_LEFT_DOUBLE'::character varying, 'CHEVRON_RIGHT_DOUBLE'::character varying, 'MENU'::character varying, 'DOTS_VERTICAL'::character varying, 'DOTS_HORIZONTAL'::character varying])::text[])))
);

ALTER TABLE public.issue_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.member (
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    owner_id bigint,
    position_id bigint,
    team_id bigint,
    version bigint,
    declared_model character varying(255),
    email character varying(255),
    language character varying(255) NOT NULL,
    member_status character varying(255) NOT NULL,
    member_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    system_role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT member_language_check CHECK (((language)::text = ANY ((ARRAY['KO'::character varying, 'EN'::character varying])::text[]))),
    CONSTRAINT member_member_status_check CHECK (((member_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying, 'DELETED'::character varying, 'PURGED'::character varying])::text[]))),
    CONSTRAINT member_member_type_check CHECK (((member_type)::text = ANY ((ARRAY['HUMAN'::character varying, 'AGENT'::character varying])::text[]))),
    CONSTRAINT member_system_role_check CHECK (((system_role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'USER'::character varying])::text[])))
);

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notification (
    is_read boolean NOT NULL,
    actor_member_id bigint,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    member_id bigint,
    receiver_member_id bigint NOT NULL,
    resource_id bigint,
    event_id uuid NOT NULL,
    actor_display_name character varying(255),
    issue_key character varying(255),
    notification_type character varying(255) NOT NULL,
    project_key character varying(255),
    receiver_email character varying(255),
    receiver_language character varying(255) NOT NULL,
    resource_type character varying(255) NOT NULL,
    message_data jsonb,
    CONSTRAINT notification_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['ISSUE_STATUS_CHANGED'::character varying, 'ISSUE_COMMENT_ADDED'::character varying, 'ISSUE_COMMENT_UPDATED'::character varying, 'ISSUE_MENTIONED'::character varying, 'ISSUE_ASSIGNED'::character varying, 'ISSUE_UNASSIGNED'::character varying, 'ISSUE_REVIEWER_ADDED'::character varying, 'ISSUE_REVIEWER_REMOVED'::character varying, 'ISSUE_REVIEW_REQUESTED'::character varying, 'ISSUE_REVIEW_SUBMITTED'::character varying, 'ISSUE_DELETED'::character varying, 'SPRINT_STARTED'::character varying, 'SPRINT_COMPLETED'::character varying, 'PROJECT_ROLE_CHANGED'::character varying])::text[]))),
    CONSTRAINT notification_receiver_language_check CHECK (((receiver_language)::text = ANY ((ARRAY['KO'::character varying, 'EN'::character varying])::text[]))),
    CONSTRAINT notification_resource_type_check CHECK (((resource_type)::text = ANY ((ARRAY['ISSUE'::character varying, 'ISSUE_COMMENT'::character varying, 'SPRINT'::character varying, 'PROJECT'::character varying, 'PROJECT_MEMBER'::character varying])::text[])))
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notification_preference (
    id bigint NOT NULL,
    receiver_member_id bigint NOT NULL,
    preferences jsonb
);

ALTER TABLE public.notification_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.personal_access_token (
    revoked boolean NOT NULL,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_used_at timestamp(6) with time zone,
    member_id bigint NOT NULL,
    revoked_at timestamp(6) with time zone,
    token_hash character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    scope character varying(255) NOT NULL,
    CONSTRAINT personal_access_token_scope_check CHECK (((scope)::text = ANY ((ARRAY['READ_ONLY'::character varying, 'READ_WRITE'::character varying])::text[])))
);

ALTER TABLE public.personal_access_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_access_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."position" (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT position_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[])))
);

ALTER TABLE public."position" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.project (
    archived boolean NOT NULL,
    soft_deleted boolean NOT NULL,
    archived_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    issue_number bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    soft_deleted_at timestamp(6) with time zone,
    sprint_number bigint NOT NULL,
    description character varying(255) NOT NULL,
    project_key character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    visibility character varying(255) NOT NULL,
    CONSTRAINT project_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.project_member (
    archived boolean NOT NULL,
    soft_deleted boolean NOT NULL,
    archived_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    project_id bigint NOT NULL,
    soft_deleted_at timestamp(6) with time zone,
    project_key character varying(255) NOT NULL,
    project_role character varying(255) NOT NULL,
    CONSTRAINT project_member_project_role_check CHECK (((project_role)::text = ANY ((ARRAY['MEMBER'::character varying, 'MANAGER'::character varying])::text[])))
);

ALTER TABLE public.project_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.project_vcs_integration (
    sync_enabled boolean NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    project_key character varying(255) NOT NULL,
    vcs_provider character varying(255) NOT NULL,
    webhook_secret character varying(255) NOT NULL,
    CONSTRAINT project_vcs_integration_vcs_provider_check CHECK (((vcs_provider)::text = ANY ((ARRAY['GITHUB'::character varying, 'GITLAB'::character varying, 'GITEA'::character varying, 'FORGEJO'::character varying])::text[])))
);

ALTER TABLE public.project_vcs_integration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_vcs_integration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.refresh_token (
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    member_id bigint NOT NULL,
    hashed_token character varying(1000) NOT NULL
);

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sprint (
    archived boolean NOT NULL,
    soft_deleted boolean NOT NULL,
    archived_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    created_by bigint,
    due_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    project_id bigint NOT NULL,
    soft_deleted_at timestamp(6) with time zone,
    sprint_number bigint NOT NULL,
    started_at timestamp(6) with time zone,
    version bigint,
    title character varying(100) NOT NULL,
    goal character varying(255) NOT NULL,
    project_key character varying(255) NOT NULL,
    sprint_status character varying(255) NOT NULL,
    CONSTRAINT sprint_sprint_status_check CHECK (((sprint_status)::text = ANY ((ARRAY['PLANNING'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.sprint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sprint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tag (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    project_id bigint NOT NULL,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    project_key character varying(255) NOT NULL,
    CONSTRAINT tag_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[])))
);

ALTER TABLE public.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.team (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT team_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[])))
);

ALTER TABLE public.team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transition_guard_config (
    execution_order integer NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    transition_id bigint NOT NULL,
    guard_type character varying(255) NOT NULL,
    guard_params jsonb,
    CONSTRAINT transition_guard_config_guard_type_check CHECK (((guard_type)::text = ANY ((ARRAY['BLOCKING_ISSUE_RESOLVE_REQUIRED'::character varying, 'APPROVAL_REQUIRED'::character varying, 'ASSIGNEE_REQUIRED'::character varying, 'CHILD_ISSUES_RESOLVE_REQUIRED'::character varying, 'LINKED_BRANCH_REQUIRED'::character varying])::text[])))
);

ALTER TABLE public.transition_guard_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transition_guard_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_attachment (
    created_at timestamp(6) with time zone,
    created_by bigint,
    file_size bigint NOT NULL,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    wiki_document_id bigint NOT NULL,
    content_type character varying(255) NOT NULL,
    original_filename character varying(255) NOT NULL,
    stored_filename character varying(255) NOT NULL,
    stored_path character varying(255) NOT NULL
);

ALTER TABLE public.wiki_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_bookmark (
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    member_id bigint NOT NULL,
    wiki_document_id bigint NOT NULL
);

ALTER TABLE public.wiki_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_document (
    archived boolean NOT NULL,
    locked boolean NOT NULL,
    major_version integer NOT NULL,
    minor_version integer NOT NULL,
    patch_version integer NOT NULL,
    soft_deleted boolean NOT NULL,
    archived_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    parent_document_id bigint,
    soft_deleted_at timestamp(6) with time zone,
    version bigint,
    content text NOT NULL,
    title character varying(255) NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE(content, ''::text)))) STORED
);

ALTER TABLE public.wiki_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_document_snapshot (
    major_version integer NOT NULL,
    minor_version integer NOT NULL,
    patch_version integer NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    wiki_document_id bigint NOT NULL,
    content text NOT NULL,
    edit_reason character varying(255) NOT NULL,
    semantic_update_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT wiki_document_snapshot_semantic_update_type_check CHECK (((semantic_update_type)::text = ANY ((ARRAY['MAJOR'::character varying, 'MINOR'::character varying, 'PATCH'::character varying])::text[])))
);

ALTER TABLE public.wiki_document_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_document_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_document_tag (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    wiki_document_id bigint NOT NULL,
    wiki_tag_id bigint NOT NULL
);

ALTER TABLE public.wiki_document_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_document_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_link (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    source_document_id bigint NOT NULL,
    target_id bigint NOT NULL,
    target_type character varying(255) NOT NULL,
    CONSTRAINT wiki_link_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['ISSUE'::character varying, 'PROJECT'::character varying, 'WIKI_DOC'::character varying])::text[])))
);

ALTER TABLE public.wiki_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wiki_tag (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    CONSTRAINT wiki_tag_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[])))
);

ALTER TABLE public.wiki_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiki_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workflow (
    system_provided boolean NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    initial_state_id bigint,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    vcs_pr_merged_transition_id bigint,
    vcs_pr_opened_transition_id bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT workflow_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[])))
);

ALTER TABLE public.workflow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workflow_state (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    workflow_id bigint NOT NULL,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    color character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    state_category character varying(255) NOT NULL,
    CONSTRAINT workflow_state_color_check CHECK (((color)::text = ANY ((ARRAY['ANSI_BLACK'::character varying, 'ANSI_RED'::character varying, 'ANSI_GREEN'::character varying, 'ANSI_YELLOW'::character varying, 'ANSI_BLUE'::character varying, 'ANSI_MAGENTA'::character varying, 'ANSI_CYAN'::character varying, 'ANSI_WHITE'::character varying, 'ANSI_BRIGHT_BLACK'::character varying, 'ANSI_BRIGHT_RED'::character varying, 'ANSI_BRIGHT_GREEN'::character varying, 'ANSI_BRIGHT_YELLOW'::character varying, 'ANSI_BRIGHT_BLUE'::character varying, 'ANSI_BRIGHT_MAGENTA'::character varying, 'ANSI_BRIGHT_CYAN'::character varying, 'ANSI_BRIGHT_WHITE'::character varying, 'PINK'::character varying, 'MAROON'::character varying, 'RED'::character varying, 'ORANGERED'::character varying, 'DARKORANGE'::character varying, 'LIMEGREEN'::character varying, 'LIGHTGREEN'::character varying, 'LIGHTYELLOW'::character varying, 'MEDIUMBLUE'::character varying, 'MIDNIGHTBLUE'::character varying, 'INDIGO'::character varying, 'MAGENTA'::character varying, 'BROWN'::character varying, 'TAN'::character varying])::text[]))),
    CONSTRAINT workflow_state_state_category_check CHECK (((state_category)::text = ANY ((ARRAY['INITIAL'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'ABORTED'::character varying])::text[])))
);

ALTER TABLE public.workflow_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workflow_transition (
    created_at timestamp(6) with time zone,
    created_by bigint,
    id bigint NOT NULL,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    source_state_id bigint NOT NULL,
    target_state_id bigint NOT NULL,
    version bigint,
    workflow_id bigint NOT NULL,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    description character varying(255) NOT NULL
);

ALTER TABLE public.workflow_transition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_transition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_event_id_key UNIQUE (event_id);

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.admin_audit_log
    ADD CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_identity
    ADD CONSTRAINT auth_identity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.email_verification_token
    ADD CONSTRAINT email_verification_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.failed_email
    ADD CONSTRAINT failed_email_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.field_option
    ADD CONSTRAINT field_option_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_attachment
    ADD CONSTRAINT issue_attachment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_branch
    ADD CONSTRAINT issue_branch_issue_id_branch_name_key UNIQUE (issue_id, branch_name);

ALTER TABLE ONLY public.issue_branch
    ADD CONSTRAINT issue_branch_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_field
    ADD CONSTRAINT issue_field_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_relation
    ADD CONSTRAINT issue_relation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_relation
    ADD CONSTRAINT issue_relation_source_issue_id_target_issue_id_key UNIQUE (source_issue_id, target_issue_id);

ALTER TABLE ONLY public.issue_reviewer
    ADD CONSTRAINT issue_reviewer_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_subscriber
    ADD CONSTRAINT issue_subscriber_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_tag
    ADD CONSTRAINT issue_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_type
    ADD CONSTRAINT issue_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_preference
    ADD CONSTRAINT notification_preference_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.personal_access_token
    ADD CONSTRAINT personal_access_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public."position"
    ADD CONSTRAINT position_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.project_vcs_integration
    ADD CONSTRAINT project_vcs_integration_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sprint
    ADD CONSTRAINT sprint_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transition_guard_config
    ADD CONSTRAINT transition_guard_config_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_identity
    ADD CONSTRAINT uk_auth_identity_provider_identifier UNIQUE (provider, identifier);

ALTER TABLE ONLY public.email_verification_token
    ADD CONSTRAINT uk_email_verification_token UNIQUE (email);

ALTER TABLE ONLY public.email_verification_token
    ADD CONSTRAINT uk_email_verification_token_value UNIQUE (token_value);

ALTER TABLE ONLY public.email_verification_token
    ADD CONSTRAINT uk_email_verification_verification_id UNIQUE (verification_id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT uk_event_receiver UNIQUE (event_id, receiver_member_id);

ALTER TABLE ONLY public.field_option
    ADD CONSTRAINT uk_field_option_issue_field_id_normalized_name UNIQUE (issue_field_id, normalized_name);

ALTER TABLE ONLY public.transition_guard_config
    ADD CONSTRAINT uk_guard_config_order UNIQUE (transition_id, execution_order);

ALTER TABLE ONLY public.transition_guard_config
    ADD CONSTRAINT uk_guard_config_type UNIQUE (transition_id, guard_type);

ALTER TABLE ONLY public.issue_field
    ADD CONSTRAINT uk_issue_field_issue_type_id_normalized_name UNIQUE (issue_type_id, normalized_name);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT uk_issue_project_id_issue_key UNIQUE (project_id, issue_key);

ALTER TABLE ONLY public.issue_reviewer
    ADD CONSTRAINT uk_issue_reviewer UNIQUE (issue_id, reviewer_id);

ALTER TABLE ONLY public.issue_subscriber
    ADD CONSTRAINT uk_issue_subscriber UNIQUE (issue_id, subscriber_id);

ALTER TABLE ONLY public.issue_tag
    ADD CONSTRAINT uk_issue_tag UNIQUE (issue_id, tag_id);

ALTER TABLE ONLY public.issue_type
    ADD CONSTRAINT uk_issue_type_normalized_name UNIQUE (normalized_name);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT uk_member_email UNIQUE (email);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT uk_member_username UNIQUE (username);

ALTER TABLE ONLY public.notification_preference
    ADD CONSTRAINT uk_notification_pref UNIQUE (receiver_member_id);

ALTER TABLE ONLY public.personal_access_token
    ADD CONSTRAINT uk_pat_member_name UNIQUE (member_id, name);

ALTER TABLE ONLY public.personal_access_token
    ADD CONSTRAINT uk_pat_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY public."position"
    ADD CONSTRAINT uk_position_name UNIQUE (normalized_name);

ALTER TABLE ONLY public.project
    ADD CONSTRAINT uk_project_key UNIQUE (project_key);

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT uk_project_member_project_id_member_id UNIQUE (project_id, member_id);

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT uk_refresh_token_member_id UNIQUE (member_id);

ALTER TABLE ONLY public.sprint
    ADD CONSTRAINT uk_sprint_number UNIQUE (project_id, sprint_number);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT uk_tag_project_id_normalized UNIQUE (project_id, normalized_name);

ALTER TABLE ONLY public.team
    ADD CONSTRAINT uk_team_name UNIQUE (normalized_name);

ALTER TABLE ONLY public.project_vcs_integration
    ADD CONSTRAINT uk_vcs_integration_project_provider UNIQUE (project_key, vcs_provider);

ALTER TABLE ONLY public.wiki_document_tag
    ADD CONSTRAINT uk_wiki_document_tag UNIQUE (wiki_document_id, wiki_tag_id);

ALTER TABLE ONLY public.wiki_link
    ADD CONSTRAINT uk_wiki_link_source_target UNIQUE (source_document_id, target_type, target_id);

ALTER TABLE ONLY public.wiki_tag
    ADD CONSTRAINT uk_wiki_tag_normalized_name UNIQUE (normalized_name);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT uk_workflow_normalized_name UNIQUE (normalized_name);

ALTER TABLE ONLY public.workflow_state
    ADD CONSTRAINT uk_workflow_state_workflow_id_normalized_name UNIQUE (workflow_id, normalized_name) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT uk_workflow_transition_edge UNIQUE (workflow_id, source_state_id, target_state_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT uk_workflow_transition_source_name UNIQUE (source_state_id, normalized_name) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.wiki_attachment
    ADD CONSTRAINT wiki_attachment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_bookmark
    ADD CONSTRAINT wiki_bookmark_member_id_wiki_document_id_key UNIQUE (member_id, wiki_document_id);

ALTER TABLE ONLY public.wiki_bookmark
    ADD CONSTRAINT wiki_bookmark_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_document
    ADD CONSTRAINT wiki_document_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_document_snapshot
    ADD CONSTRAINT wiki_document_snapshot_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_document_snapshot
    ADD CONSTRAINT wiki_document_snapshot_wiki_document_id_major_version_minor_key UNIQUE (wiki_document_id, major_version, minor_version, patch_version);

ALTER TABLE ONLY public.wiki_document_tag
    ADD CONSTRAINT wiki_document_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_link
    ADD CONSTRAINT wiki_link_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wiki_tag
    ADD CONSTRAINT wiki_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_initial_state_id_key UNIQUE (initial_state_id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_state
    ADD CONSTRAINT workflow_state_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT workflow_transition_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_vcs_pr_merged_transition_id_key UNIQUE (vcs_pr_merged_transition_id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_vcs_pr_opened_transition_id_key UNIQUE (vcs_pr_opened_transition_id);

CREATE INDEX idx_comment_author_id ON public.comment USING btree (author_id);

CREATE INDEX idx_comment_issue_id ON public.comment USING btree (issue_id);

CREATE INDEX idx_comment_parent_comment_id ON public.comment USING btree (parent_comment_id);

CREATE INDEX idx_field_option_issue_field_id ON public.field_option USING btree (issue_field_id);

CREATE INDEX idx_issue_current_state_id ON public.issue USING btree (current_state_id);

CREATE INDEX idx_issue_project_priority_due ON public.issue USING btree (project_id, priority, due_at);

CREATE INDEX idx_issue_reviewer_issue_id ON public.issue_reviewer USING btree (issue_id);

CREATE INDEX idx_issue_reviewer_reviewer_id ON public.issue_reviewer USING btree (reviewer_id);

CREATE INDEX idx_issue_search_vector ON public.issue USING gin (search_vector);

CREATE INDEX idx_issue_subscriber_issue_id ON public.issue_subscriber USING btree (issue_id);

CREATE INDEX idx_issue_subscriber_subscriber_id ON public.issue_subscriber USING btree (subscriber_id);

CREATE INDEX idx_issue_tag_issue_id ON public.issue_tag USING btree (issue_id);

CREATE INDEX idx_issue_tag_tag_id ON public.issue_tag USING btree (tag_id);

CREATE INDEX idx_notification_receiver_is_read_id ON public.notification USING btree (receiver_member_id, is_read, id DESC);

CREATE INDEX idx_project_member_member_id ON public.project_member USING btree (member_id);

CREATE INDEX idx_wiki_document_search_vector ON public.wiki_document USING gin (search_vector);

CREATE INDEX idx_wiki_document_tag_document_id ON public.wiki_document_tag USING btree (wiki_document_id);

CREATE INDEX idx_wiki_document_tag_tag_id ON public.wiki_document_tag USING btree (wiki_tag_id);

CREATE INDEX idx_wiki_tag_normalized_name_trgm ON public.wiki_tag USING gin (normalized_name public.gin_trgm_ops);

CREATE UNIQUE INDEX uk_sprint_active_per_project ON public.sprint USING btree (project_id) WHERE (((sprint_status)::text = 'ACTIVE'::text) AND (soft_deleted = false));

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT fk103dwxad12nbaxtmnwus4eft2 FOREIGN KEY (project_id) REFERENCES public.project(id);

ALTER TABLE ONLY public.wiki_bookmark
    ADD CONSTRAINT fk29r0wm296u4ib3343kbdradl7 FOREIGN KEY (wiki_document_id) REFERENCES public.wiki_document(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fk2bam3knj13ijq6eiskx55xtqh FOREIGN KEY (author_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.issue_field
    ADD CONSTRAINT fk2fdtr1bcf9tlgwy9tltnaait1 FOREIGN KEY (issue_type_id) REFERENCES public.issue_type(id);

ALTER TABLE ONLY public.issue_relation
    ADD CONSTRAINT fk3lxchr0q349wa5qfgtbckhml6 FOREIGN KEY (source_issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.transition_guard_config
    ADD CONSTRAINT fk4wmfbcp33x1521kr9jinuovuc FOREIGN KEY (transition_id) REFERENCES public.workflow_transition(id);

ALTER TABLE ONLY public.issue_type
    ADD CONSTRAINT fk5ak3tn60o0pmpq4h2lbfp11mi FOREIGN KEY (workflow_id) REFERENCES public.workflow(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fk5k39vkuty9g6w3n7iwye1nh0i FOREIGN KEY (sprint_id) REFERENCES public.sprint(id);

ALTER TABLE ONLY public.auth_identity
    ADD CONSTRAINT fk7hbhjmd3klwtrx3a37sd8wh0f FOREIGN KEY (member_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT fk7ihvexg9thj8dwmqxuvdiw8qq FOREIGN KEY (initial_state_id) REFERENCES public.workflow_state(id);

ALTER TABLE ONLY public.wiki_document_tag
    ADD CONSTRAINT fk7qtd0dkat0h93jtn7hle67qxl FOREIGN KEY (wiki_document_id) REFERENCES public.wiki_document(id);

ALTER TABLE ONLY public.wiki_document_snapshot
    ADD CONSTRAINT fk9hqnv36n5fi8bvdurnygll3w2 FOREIGN KEY (wiki_document_id) REFERENCES public.wiki_document(id);

ALTER TABLE ONLY public.wiki_document_tag
    ADD CONSTRAINT fk9rsepgk9nmw8buf4ogktbgt47 FOREIGN KEY (wiki_tag_id) REFERENCES public.wiki_tag(id);

ALTER TABLE ONLY public.issue_tag
    ADD CONSTRAINT fka88jn6xqvbgumurvrbo8qqk80 FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkaipd2dahs3kffrqlb42hbthip FOREIGN KEY (current_state_id) REFERENCES public.workflow_state(id);

ALTER TABLE ONLY public.workflow_state
    ADD CONSTRAINT fkaqkqcopgu8q3inq8w1gj9d0ma FOREIGN KEY (workflow_id) REFERENCES public.workflow(id);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT fkbyy56vice9njgl86752up8120 FOREIGN KEY (project_id) REFERENCES public.project(id);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT fkcbkb0poq30jh6my2b38iwcq9b FOREIGN KEY (position_id) REFERENCES public."position"(id);

ALTER TABLE ONLY public.personal_access_token
    ADD CONSTRAINT fkcjb1uxlf2a77ucxrxp4wbh3gh FOREIGN KEY (member_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT fkcjte2jn9pvo9ud2hyfgwcja0k FOREIGN KEY (team_id) REFERENCES public.team(id);

ALTER TABLE ONLY public.issue_relation
    ADD CONSTRAINT fkcl30rwf14sss0btg3xt6h9rsy FOREIGN KEY (target_issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkcombytcpeogaqi2012phvvvhy FOREIGN KEY (project_id) REFERENCES public.project(id);

ALTER TABLE ONLY public.sprint
    ADD CONSTRAINT fkerwve0blrvfhqm1coxo69f0xr FOREIGN KEY (project_id) REFERENCES public.project(id);

ALTER TABLE ONLY public.issue_reviewer
    ADD CONSTRAINT fkfl4jvm7vqi5bo3vfhx0k98kg9 FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.issue_attachment
    ADD CONSTRAINT fkftrgfd0qxhr6u47pr6ja28u57 FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT fkgjbk3i3vari0hun2buf3osbw FOREIGN KEY (source_state_id) REFERENCES public.workflow_state(id);

ALTER TABLE ONLY public.issue_branch
    ADD CONSTRAINT fkh4cq4hqx20v8lkf1c8pofh721 FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkhvh0e2ybgg16bpu229a5teje7 FOREIGN KEY (parent_comment_id) REFERENCES public.comment(id);

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT fkilusx84svugdln73un4w2euar FOREIGN KEY (member_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT fkjtgc5t3un3kchin1ij7dxbwff FOREIGN KEY (owner_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.issue_tag
    ADD CONSTRAINT fkk8wi7gufhebbkl9lay3cugi06 FOREIGN KEY (tag_id) REFERENCES public.tag(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkkbd7nxp2aq0bc4yomxoafmysg FOREIGN KEY (issue_type_id) REFERENCES public.issue_type(id);

ALTER TABLE ONLY public.issue_subscriber
    ADD CONSTRAINT fkl1q2l75o4gt9dxlr3cairv0e3 FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.wiki_attachment
    ADD CONSTRAINT fkmjnepkdanw9b48j1mykc9vj6c FOREIGN KEY (wiki_document_id) REFERENCES public.wiki_document(id);

ALTER TABLE ONLY public.wiki_link
    ADD CONSTRAINT fknuttgfi88e8wrm4ej7v6inkvr FOREIGN KEY (source_document_id) REFERENCES public.wiki_document(id);

ALTER TABLE ONLY public.field_option
    ADD CONSTRAINT fkokej9sc544xrugn64ow7ejkld FOREIGN KEY (issue_field_id) REFERENCES public.issue_field(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkomjg70m9sundkar1el2rtonrn FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT fkoqcdeu7kkl9nwpwwmsjx78sgv FOREIGN KEY (workflow_id) REFERENCES public.workflow(id);

ALTER TABLE ONLY public.issue_reviewer
    ADD CONSTRAINT fkoqnub76f4t3t5qlnxwp38wg0w FOREIGN KEY (reviewer_id) REFERENCES public.project_member(id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT fkpevc79ta533oaopkgxwfpto3s FOREIGN KEY (vcs_pr_merged_transition_id) REFERENCES public.workflow_transition(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkpfppd5ngu54pjokhmg0ovseoo FOREIGN KEY (assignee_id) REFERENCES public.project_member(id);

ALTER TABLE ONLY public.workflow_transition
    ADD CONSTRAINT fkphc46wh9ho7fg4ueeobdhtr3q FOREIGN KEY (target_state_id) REFERENCES public.workflow_state(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkrto8oobk4xfwqx05x3s99bvtf FOREIGN KEY (parent_issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.issue_subscriber
    ADD CONSTRAINT fks56oi7x8rio7rfq7v6ui01xed FOREIGN KEY (subscriber_id) REFERENCES public.project_member(id);

ALTER TABLE ONLY public.wiki_document
    ADD CONSTRAINT fkscu8tyjxdjg0tb5oxh44lybye FOREIGN KEY (parent_document_id) REFERENCES public.wiki_document(id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT fkt73p0ar5q3d32qggcy2b9unxg FOREIGN KEY (vcs_pr_opened_transition_id) REFERENCES public.workflow_transition(id);


--
-- Foreign-key indexes
--
CREATE INDEX idx_auth_identity_member_id ON public.auth_identity USING btree (member_id);
CREATE INDEX idx_issue_assignee_id ON public.issue USING btree (assignee_id);
CREATE INDEX idx_issue_issue_type_id ON public.issue USING btree (issue_type_id);
CREATE INDEX idx_issue_parent_issue_id ON public.issue USING btree (parent_issue_id);
CREATE INDEX idx_issue_sprint_id ON public.issue USING btree (sprint_id);
CREATE INDEX idx_issue_attachment_issue_id ON public.issue_attachment USING btree (issue_id);
CREATE INDEX idx_issue_relation_target_issue_id ON public.issue_relation USING btree (target_issue_id);
CREATE INDEX idx_issue_type_workflow_id ON public.issue_type USING btree (workflow_id);
CREATE INDEX idx_member_owner_id ON public.member USING btree (owner_id);
CREATE INDEX idx_member_position_id ON public.member USING btree (position_id);
CREATE INDEX idx_member_team_id ON public.member USING btree (team_id);
CREATE INDEX idx_wiki_attachment_wiki_document_id ON public.wiki_attachment USING btree (wiki_document_id);
CREATE INDEX idx_wiki_bookmark_wiki_document_id ON public.wiki_bookmark USING btree (wiki_document_id);
CREATE INDEX idx_wiki_document_parent_document_id ON public.wiki_document USING btree (parent_document_id);
CREATE INDEX idx_workflow_transition_target_state_id ON public.workflow_transition USING btree (target_state_id);
