-- AI model catalog (globally admin-managed, mirrors position/team).
CREATE TABLE public.ai_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone,
    created_by bigint,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    version bigint,
    display_name character varying(64) NOT NULL,
    normalized_name character varying(64) NOT NULL,
    description character varying(255) NOT NULL,
    color character varying(255) NOT NULL,
    CONSTRAINT ai_model_pkey PRIMARY KEY (id),
    CONSTRAINT uk_ai_model_name UNIQUE (normalized_name),
    CONSTRAINT ai_model_color_check CHECK (((color)::text = ANY ((ARRAY[
        'ANSI_BLACK', 'ANSI_RED', 'ANSI_GREEN', 'ANSI_YELLOW', 'ANSI_BLUE', 'ANSI_MAGENTA', 'ANSI_CYAN',
        'ANSI_WHITE', 'ANSI_BRIGHT_BLACK', 'ANSI_BRIGHT_RED', 'ANSI_BRIGHT_GREEN', 'ANSI_BRIGHT_YELLOW',
        'ANSI_BRIGHT_BLUE', 'ANSI_BRIGHT_MAGENTA', 'ANSI_BRIGHT_CYAN', 'ANSI_BRIGHT_WHITE', 'PINK', 'MAROON',
        'RED', 'ORANGERED', 'DARKORANGE', 'LIMEGREEN', 'LIGHTGREEN', 'LIGHTYELLOW', 'MEDIUMBLUE', 'MIDNIGHTBLUE',
        'INDIGO', 'MAGENTA', 'BROWN', 'TAN']::character varying[])::text[])))
);

-- Member: replace the free-text declared_model with a catalog FK, and add agent_type + description.
ALTER TABLE public.member ADD COLUMN agent_type character varying(255);
ALTER TABLE public.member ADD COLUMN model_id bigint;
ALTER TABLE public.member ADD COLUMN description character varying(255);
ALTER TABLE public.member DROP COLUMN declared_model;

ALTER TABLE public.member
    ADD CONSTRAINT member_agent_type_check
    CHECK (agent_type IS NULL OR (agent_type)::text = ANY ((ARRAY[
        'DEVELOPMENT', 'PLANNING', 'MANAGEMENT', 'DESIGN', 'QA', 'GENERAL']::character varying[])::text[]));

ALTER TABLE public.member
    ADD CONSTRAINT fk_member_model FOREIGN KEY (model_id) REFERENCES public.ai_model(id);

CREATE INDEX idx_member_model_id ON public.member (model_id);
