-- Inbound VCS webhook deliveries, stored before processing.
-- Serves three purposes at once: the unique delivery id drops provider redeliveries, the retained payload
-- lets a failed delivery be retried (GitHub does not guarantee it resends one for us), and the row is the
-- history an operator needs to see why a push or PR did not attach to an issue.
CREATE TABLE public.vcs_webhook_delivery (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone,
    last_modified_at timestamp(6) with time zone,
    vcs_provider character varying(255) NOT NULL,
    delivery_id character varying(255) NOT NULL,
    project_key character varying(255) NOT NULL,
    event_type character varying(255) NOT NULL,
    payload text NOT NULL,
    status character varying(255) NOT NULL,
    attempt_count integer NOT NULL,
    result_detail character varying(500),
    last_error character varying(1000),
    next_attempt_at timestamp(6) with time zone,
    processed_at timestamp(6) with time zone,
    CONSTRAINT vcs_webhook_delivery_pkey PRIMARY KEY (id),
    CONSTRAINT uk_vcs_delivery_provider_delivery_id UNIQUE (vcs_provider, delivery_id),
    CONSTRAINT vcs_webhook_delivery_vcs_provider_check CHECK (((vcs_provider)::text = ANY ((ARRAY[
        'GITHUB', 'GITLAB', 'GITEA', 'FORGEJO']::character varying[])::text[]))),
    CONSTRAINT vcs_webhook_delivery_status_check CHECK (((status)::text = ANY ((ARRAY[
        'RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED', 'DEAD']::character varying[])::text[])))
);

-- Drives the retry sweep: due deliveries are looked up by status + next attempt time.
CREATE INDEX idx_vcs_delivery_retry ON public.vcs_webhook_delivery (status, next_attempt_at);

-- Drives per-project delivery history, newest first.
CREATE INDEX idx_vcs_delivery_project ON public.vcs_webhook_delivery (project_key, created_at);
