-- Pull requests linked to an issue, mirroring issue_branch.
-- Kept as current state rather than history: a PR that is opened, closed and reopened stays one row whose
-- state changes, so the issue detail can show what is open now without replaying the activity log.
CREATE TABLE public.issue_pull_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone,
    created_by bigint,
    last_modified_at timestamp(6) with time zone,
    last_modified_by bigint,
    issue_id bigint NOT NULL,
    pr_number integer NOT NULL,
    title character varying(255) NOT NULL,
    url character varying(255) NOT NULL,
    author_name character varying(255),
    state character varying(255) NOT NULL,
    last_event_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT issue_pull_request_pkey PRIMARY KEY (id),
    CONSTRAINT issue_pull_request_issue_id_pr_number_key UNIQUE (issue_id, pr_number),
    CONSTRAINT issue_pull_request_state_check CHECK (((state)::text = ANY ((ARRAY[
        'OPEN', 'CLOSED', 'MERGED']::character varying[])::text[])))
);

ALTER TABLE ONLY public.issue_pull_request
    ADD CONSTRAINT fk_issue_pull_request_issue FOREIGN KEY (issue_id) REFERENCES public.issue(id);

-- The issue detail loads a single issue's pull requests.
CREATE INDEX idx_issue_pull_request_issue ON public.issue_pull_request (issue_id);
