package com.tissue.api.notification.domain.enums;

public enum NotificationType {
	ISSUE_CREATED,
	ISSUE_PARENT_ASSIGNED,
	ISSUE_PARENT_REMOVED,
	ISSUE_UPDATED,
	ISSUE_STATUS_CHANGED,
	ISSUE_COMMENT_ADDED,
	ISSUE_ASSIGNED,
	ISSUE_REVIEWER_ADDED,
	REVIEW_REQUESTED,
	REVIEW_SUBMITTED,
	REVIEW_COMMENT_ADDED,
	SPRINT_STARTED,
	SPRINT_ENDED,
	INVITATION_RECEIVED,
	MEMBER_JOINED_WORKSPACE,
	WORKSPACE_MEMBER_ROLE_CHANGED
}
