# Default
# active: dev
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:tcp://localhost:1521/taskmanager-local-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
---
# Development
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost:1521/taskmanager-dev-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
---
# Production
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging.level:
  org.hibernate.SQL: off
  org.hibernate.type.descriptor.sql.BasicBinder: off
  org.hibernate.orm.jdbc.bind: off
  org.hibernate.stat: off