[versions]
springBoot = "3.5.11"
springDependencyManagement = "1.1.7"

jacksonDatabindNullable = "0.2.7"
jspecify = "1.0.0"
commonsText = "1.14.0"
commonsLang3 = "3.18.0"
commonsCodec = "1.17.2"
tika = "3.2.2"
springdocOpenapi = "2.8.16"
springdocOpenapiGradle = "1.9.0"
awsSdkS3 = "2.31.1"
logstashLogbackEncoder = "8.0"

checkstyle = "12.3.0"
spotless = "8.1.0"
errorPronePlugin = "4.3.0"
nullAway = "0.12.15"
errorProneCore = "2.45.0"

[libraries]
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }

spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }
spring-boot-starter-thymeleaf = { group = "org.springframework.boot", name = "spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-aop = { group = "org.springframework.boot", name = "spring-boot-starter-aop" }
spring-boot-starter-mail = { group = "org.springframework.boot", name = "spring-boot-starter-mail" }
spring-boot-starter-cache = { group = "org.springframework.boot", name = "spring-boot-starter-cache" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
spring-boot-docker-compose = { group = "org.springframework.boot", name = "spring-boot-docker-compose" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-testcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers" }
spring-boot-starter-oauth2-resource-server = { group = "org.springframework.boot", name = "spring-boot-starter-oauth2-resource-server" }

spring-web = { group = "org.springframework", name = "spring-web" }
spring-retry = { group = "org.springframework.retry", name = "spring-retry" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }
spring-security-crypto = { group = "org.springframework.security", name = "spring-security-crypto" }
spring-security-core = { group = "org.springframework.security", name = "spring-security-core" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine" }
postgresql = { group = "org.postgresql", name = "postgresql" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
lombok = { group = "org.projectlombok", name = "lombok" }

# Micrometer
micrometer-tracing-bridge-brave = { group = "io.micrometer", name = "micrometer-tracing-bridge-brave" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus" }

# Logging
logstash-logback-encoder = { group = "net.logstash.logback", name = "logstash-logback-encoder", version.ref = "logstashLogbackEncoder" }

# Testcontainers
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql" }

# Common
jackson-databind-nullable = { group = "org.openapitools", name = "jackson-databind-nullable", version.ref = "jacksonDatabindNullable" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commonsText" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec"}
commons-pool2 = { group = "org.apache.commons", name = "commons-pool2" }
tika-core = { group = "org.apache.tika", name = "tika-core", version.ref = "tika" }

# API Documentation
swagger-annotations = { group = "io.swagger.core.v3", name = "swagger-annotations-jakarta", version = "2.2.43" }
springdoc-openapi-starter-webmvc-api = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-api", version.ref = "springdocOpenapi" }

# S3
aws-sdk-s3 = { group = "software.amazon.awssdk", name = "s3", version.ref = "awsSdkS3" }

# Code Quality
nullaway = { group = "com.uber.nullaway", name = "nullaway", version.ref = "nullAway" }
errorprone-core = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorProneCore" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorPronePlugin" }
springdoc-openapi-gradle = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "springdocOpenapiGradle" }
