project(':tissue-core') {
  dependencies {
    api libs.spring.boot.starter.data.jpa
    api libs.spring.web

    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.aop
    implementation libs.spring.retry

    api libs.jspecify
    api libs.jackson.databind.nullable

    api libs.commons.lang3
    api libs.commons.text

    // TODO: use version catalog
    implementation 'org.springframework.security:spring-security-core'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.springframework.security:spring-security-oauth2-core'
  }

  bootJar.enabled = false
  jar.enabled = true
}
