package com.tissue.activitylog.domain.enums;

public enum ActivityType {
    ISSUE_CREATED,
    ISSUE_UPDATED,
    ISSUE_DELETED,
    ISSUE_ASSIGNED,
    ISSUE_UNASSIGNED,
    ISSUE_STATUS_CHANGED,
    ISSUE_REPORTER_CHANGED,
    ISSUE_STORY_POINT_CHANGED,
    ISSUE_PARENT_CHANGED,
    ISSUE_RELATION_ADDED,
    ISSUE_RELATION_REMOVED,
    ISSUE_REVIEW_REQUESTED,
    ISSUE_REVIEW_SUBMITTED,
    ISSUE_REVIEWER_ADDED,
    ISSUE_REVIEWER_REMOVED,
    ISSUE_COMMENT_ADDED,
    SPRINT_STARTED,
    SPRINT_COMPLETED;
}
