project(':tissue-bootstrap') {
  apply plugin: 'org.springdoc.openapi-gradle-plugin'

  dependencies {
    implementation project(':tissue-core')
    implementation project(':tissue-security')
    implementation project(':tissue-notification')

    implementation libs.spring.boot.starter.web
    implementation libs.springdoc.openapi.starter.webmvc.api
    implementation libs.spring.boot.starter.actuator
    implementation libs.micrometer.registry.prometheus
    implementation libs.logstash.logback.encoder

    testImplementation libs.spring.boot.starter.data.redis
    testImplementation libs.spring.boot.testcontainers
    testImplementation libs.testcontainers.postgresql

    developmentOnly libs.spring.boot.devtools
    developmentOnly libs.spring.boot.docker.compose
  }

  bootJar.enabled = true
  jar.enabled = false

  openApi {
    apiDocsUrl.set("http://localhost:8080/v3/api-docs")
    outputDir.set(file("$rootDir/../docs"))
    outputFileName.set("api-docs.json")
    waitTimeInSeconds.set(60)
    customBootRun {
      args.set([
        "--spring.docker.compose.file=${rootDir}/compose.yaml".toString(),
        "--spring.profiles.active=local",
        "--server.port=8080"
      ])
    }
  }

  afterEvaluate {
    tasks.named('forkedSpringBootRun').configure {
      dependsOn ':tissue-core:jar', ':tissue-security:jar', ':tissue-notification:jar'
    }
  }
}
