blank_issues_enabled: false
contact_links:
  - name: Q&A
    url: https://github.com/kiseki1011/TISSUE/discussions/categories/q-a
    about: If you have any questions, ask in Discussions/Q&A.

  - name: Ideas
    url: https://github.com/kiseki1011/TISSUE/discussions/categories/ideas
    about: Discuss rough ideas before opening a feature request.

  - name: General
    url: https://github.com/kiseki1011/TISSUE/discussions/categories/general
    about: Anything else.
