project(':tissue-api') {
  dependencies {
    implementation project(':tissue-core')
    implementation project(':tissue-common')

    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.validation
  }

  bootJar.enabled = false
  jar.enabled = true
}
