package com.tissue.feature.notification.domain.enums;

public enum NotificationType {
    ISSUE_CREATED,
    ISSUE_UPDATED,
    ISSUE_STATUS_CHANGED,
    ISSUE_COMMENT_ADDED,
    ISSUE_COMMENT_UPDATED,
    ISSUE_MENTIONED,
    ISSUE_ASSIGNED,
    ISSUE_UNASSIGNED,
    ISSUE_REVIEWER_ADDED,
    ISSUE_REVIEWER_REMOVED,
    ISSUE_REVIEW_REQUESTED,
    ISSUE_REVIEW_SUBMITTED,
    ISSUE_DELETED,
    SPRINT_STARTED,
    SPRINT_COMPLETED,
    MEMBER_JOINED_PROJECT,
    PROJECT_ROLE_CHANGED;
}
