# Default
spring:
  profiles:
    active: local

---
# Local & Test
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost:1521/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate:
      format_sql: true
      show-sql: true
      highlight_sql: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE

  messages:
    basename: messages # messages.properties, messages_ko.properties 등의 기본 경로 설정
    encoding: UTF-8    # 인코딩 설정
    fallback-to-system-locale: false  # 시스템 로케일로 폴백하지 않도록 설정
    cache-duration: 0  # 캐시 저장 안함

api:
  issue:
    circular-dependency-cache:
      size: 1000
      duration: 1

---
# Development
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/devdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    cache-duration: 0

api:
  issue:
    circular-dependency-cache:
      size: 1000
      duration: 1

---
# Production
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/proddb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  messages:
    cache-duration: -1 # 캐시 영구 저장

logging.level:
  org.hibernate.SQL: off
  org.hibernate.type.descriptor.sql.BasicBinder: off
  org.hibernate.orm.jdbc.bind: off
  org.hibernate.stat: off

api:
  issue:
    circular-dependency-cache:
      size: 1000
      duration: 1