# Default
spring:
  profiles:
    active: local

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate:
      format_sql: true
      show-sql: true
      highlight_sql: true
      default_batch_fetch_size: 100

tissue:
  base-url: http://localhost:8080

  system:
    mode: PUBLIC
    server-name: "Tissue Official Server"

  security:
    auth-providers:
      - EMAIL
      - GOOGLE
      - GITHUB
    jwt:
      secret: ${JWT_SECRET:very_secret_key_that_is_at_least_32_chars_long_123}
      access-token-validity: 3600        # 1 hour
      refresh-token-validity: 604800     # 1 week
      elevated-token-validity: 600       # 10 minutes

  email:
    sender: ${tissue.email.sender:noreply@tissue.com}
    provider: dummy
    verification:
      # change "strategy" -> "db-type" or "db"
      strategy: redis  # or rdb(postgresql)
      ttl: 1800s       # 30 minutes
      success-url: ${tissue.base-url}/members/verification/success
      failure-url: ${tissue.base-url}/members/verification/fail
      verification-url: ${tissue.base-url}/api/v1/members/verification/verify

  notification:
    email:
      concurrency: 20
      retry-interval-ms: 180000 # 3 minutes
    executor:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 100
      thread-name-prefix: Notification-

  member:
    policy:
      allow-signup: true
      max-owned-workspaces: 10
      max-joined-workspaces: 10

  workspace:
    policy:
      max-members: 1000

  project:
    policy:
      max-members: 1000
      # max-issues: 1000000
      # max-sprints: 100000
      # max-issue-fields: 1000
      # max-issue-types: 1000
      # max-workflows: 1000

  issue:
    policy:
      max-reviewers: 10
      type:
      # max-fields-per-issue-type: 20
      field:
        max-enum-options: 100
        decimal:
          scale: 6
          rounding: HALF_UP
          digits:
            integer: 14
            fraction: 6
    circular-dependency-cache:
      size: 1000
      duration: 1

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE

---
# Local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/tissue_local
    username: developer
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${LOCAL_REDIS_PASSWORD:}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:missing_username}
    password: ${GMAIL_PASSWORD:missing_password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

---
# Development
spring:
  config:
    activate:
      on-profile: dev

  # use postgres
  datasource:
    url: jdbc:mysql://localhost:3306/tissue_local
    username: developer
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

---
# Production
spring:
  config:
    activate:
      on-profile: prod

  # use postgres
  datasource:
    url: jdbc:mysql://localhost:3306/tissue_local
    username: developer
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  messages:
    cache-duration: -1

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.orm.jdbc.bind: off
    org.hibernate.stat: off
