package com.tissue.notification.domain.enums;

public enum NotificationType {
    ISSUE_CREATED,
    ISSUE_PARENT_ASSIGNED,
    ISSUE_PARENT_REMOVED,
    ISSUE_UPDATED,
    ISSUE_STATUS_CHANGED,
    ISSUE_COMMENT_ADDED,
    ISSUE_ASSIGNED,
    ISSUE_UNASSIGNED,
    ISSUE_REVIEWER_ADDED,
    ISSUE_REVIEWER_REMOVED,
    ISSUE_REVIEW_REQUESTED,
    ISSUE_REVIEW_SUBMITTED,
    ISSUE_REPORTER_CHANGED,
    ISSUE_DELETED,
    SPRINT_STARTED,
    SPRINT_COMPLETED,
    MEMBER_JOINED_WORKSPACE,
    WORKSPACE_ROLE_CHANGED,
    PROJECT_ROLE_CHANGED;
    // TODO: MENTIONED_IN_COMMENT?
}
