package domain

import "time"

// Token scope values, mirroring the backend PatScope enum.
const (
	ScopeReadOnly  = "READ_ONLY"
	ScopeReadWrite = "READ_WRITE"
)

// AgentTypes are the functional categories an agent can have, mirroring the backend AgentType enum.
var AgentTypes = []string{"DEVELOPMENT", "PLANNING", "MANAGEMENT", "DESIGN", "QA", "GENERAL"}

// Agent is an AI/automation account owned by the caller (a Member with memberType=AGENT).
// Agents inherit the owner's project memberships. There is no per-project scoping.
type Agent struct {
	ID          int64
	Name        string // owner-facing name (letters and spaces only, unique among the owner's agents)
	Username    string // globally unique handle generated by the server, like agent-alice-build
	AgentType   string // one of AgentTypes; "" when unset
	ModelID     int64  // catalog model id, 0 when none
	ModelName   string // catalog model name, "" when none
	ModelColor  string // ColorType name of the model, "" when none
	Description string // free-form description, "" when none
	CreatedAt   time.Time
}

// AiModel is a catalog entry (globally admin-managed) that an agent's model references.
type AiModel struct {
	ID          int64
	Name        string
	Description string
	Color       string // ColorType name
}

// Token is a personal access token (PAT) issued to an agent. Its raw secret is never returned
// after creation. This carries only metadata.
type Token struct {
	ID         int64
	Name       string
	Scope      string // ScopeReadOnly | ScopeReadWrite
	Revoked    bool
	CreatedAt  time.Time
	ExpiresAt  time.Time // zero = never expires
	LastUsedAt time.Time // zero = never used
}

func (t Token) IsUsable(now time.Time) bool {
	if t.Revoked {
		return false
	}
	if !t.ExpiresAt.IsZero() && !now.Before(t.ExpiresAt) {
		return false
	}
	return true
}

// IssuedToken is a freshly created token whose raw secret is available exactly once, at creation.
type IssuedToken struct {
	Secret string // the raw bearer token, shown to the user once and never retrievable again
	Token  Token
}
