dependencies {
  implementation project(':tissue-core')

  implementation libs.spring.boot.starter.security
  implementation libs.spring.boot.starter.web
  implementation libs.spring.boot.starter.validation

  implementation libs.spring.boot.starter.oauth2.resource.server
  implementation libs.oauth2.oidc.sdk

  implementation libs.spring.boot.starter.data.redis

  testImplementation libs.wiremock.standalone
}

bootJar.enabled = false
jar.enabled = true
