package com.tissue.feature.agent.application.dto;

import com.tissue.feature.agent.domain.AgentType;
import com.tissue.feature.agent.model.application.dto.response.AiModelSummary;
import com.tissue.feature.member.domain.Member;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import lombok.Builder;
import org.jspecify.annotations.Nullable;

@Builder
public record AgentResponse(
        @Schema(description = "Agent member id", example = "67")
        Long id,

        @Schema(description = "Owner facing agent name", example = "Mycodebot")
        String name,

        @Schema(description = "Globally unique handle generated by the server", example = "agent-gildong-code-reviewer")
        String username,

        @Schema(description = "Functional category of the agent", example = "DEVELOPMENT") @Nullable
        AgentType agentType,

        @Schema(description = "AI model the agent runs") @Nullable
        AiModelSummary model,

        @Schema(description = "Free-form description of the agent") @Nullable
        String description,

        Instant createdAt) {

    public static AgentResponse from(Member agent) {
        return AgentResponse.builder()
                .id(agent.getId())
                .name(agent.getName())
                .username(agent.getUsername())
                .agentType(agent.getAgentType())
                .model(agent.getModel() == null ? null : AiModelSummary.from(agent.getModel()))
                .description(agent.getDescription())
                .createdAt(agent.getCreatedAt())
                .build();
    }
}
