package com.tissue.feature.member.application.dto;

import com.tissue.feature.member.domain.Member;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import lombok.Builder;
import org.jspecify.annotations.Nullable;

@Builder
public record AgentResponse(
        @Schema(description = "Agent member id", example = "67")
        Long id,

        @Schema(description = "Owner facing agent name", example = "Mycodebot")
        String name,

        @Schema(description = "Globally unique handle generated by the server", example = "agent-gildong-code-reviewer")
        String username,

        @Schema(description = "Model of the agent", example = "gemini-pro-3-1") @Nullable
        String declaredModel,

        Instant createdAt) {

    public static AgentResponse from(Member agent) {
        return AgentResponse.builder()
                .id(agent.getId())
                .name(agent.getName())
                .username(agent.getUsername())
                .declaredModel(agent.getDeclaredModel())
                .createdAt(agent.getCreatedAt())
                .build();
    }
}
